### ISSUE TITLE
vscode version not compatible

### ISSUE THREAD

**Issue by faga295** [johnsoncodehk/vscode-code-spotlight#1]
![image](https://user-images.githubusercontent.com/87003751/223444956-3ff49598-0eea-4101-bdad-6b783c8f8398.png)
which version should I use?

**Comment by johnsoncodehk** [comment]
You need to update VSCode to 1.76.0.

https://github.com/johnsoncodehk/vscode-code-spotlight/blob/e631ce2d6c28e867e4b874cad354da5310d4291e/package.json#L16
